base_url = "https://ankita.wiki"
compile_sass = true
build_search_index = false
theme = "particle"

[markdown]
highlight_code = true

[extra]
# Site settings
description = "My portfolio on the web."

# User settings
username = ""
user_description = "Student | Aspiring Software Developer"
user_title = "Ankita Kumari"
email = "rathorankita4u@gmail.com"
twitter_username = "lorem_ipsum"
github_username = "lorem_ipsum"
gplus_username = "lorem_ipsum"
